0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,17 +1,24 @@
 #!/bin/bash
 
-# Check if the number of parameters is less than 4
-if [ "$#" -ne 4 ]; then
+# Check if less than 4 parameters are passed
+if [ "$#" -lt 4 ]; then
   echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 1
 fi
 
 # Assign parameters to variables
-PATH_TO_FILE=$1
-IP=$2
+FILE_PATH=$1
+SERVER_IP=$2
 USERNAME=$3
-PATH_TO_SSH_KEY=$4
+SSH_KEY_PATH=$4
 
-# Transfer the file using scp with strict host key checking disabled
-scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"
+# Use scp to transfer the file to the user's home directory on the server
+scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"
+
+# Check if the scp command was successful
+if [ $? -eq 0 ]; then
+  echo "File transfer completed successfully."
+else
+  echo "File transfer failed."
+fi
 
