2-setup_a_domain_name

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -12,6 +12,18 @@ SERVER_IP=$2
 USERNAME=$3
 SSH_KEY_PATH=$4
 
+# Check if the file to transfer exists
+if [ ! -f "$FILE_PATH" ]; then
+  echo "Error: File '$FILE_PATH' does not exist."
+  exit 1
+fi
+
+# Check if the SSH private key file exists
+if [ ! -f "$SSH_KEY_PATH" ]; then
+  echo "Error: SSH key '$SSH_KEY_PATH' does not exist."
+  exit 1
+fi
+
 # Use scp to transfer the file to the user's home directory on the server
 scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"
 
